= 条件评估报告 (conditions)

`conditions` 端点提供了关于配置类和自动配置类条件评估的信息。

== 检索报告

要检索报告，可以按照以下基于 curl 的示例，向 `/actuator/conditions` 发起一个 `GET` 请求：

[source,bash]
----
curl 'http://localhost:8080/actuator/conditions' -i -X GET
----

返回的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 3705

{
  "contexts" : {
    "application" : {
      "positiveMatches" : {
        "EndpointAutoConfiguration#endpointOperationParameterMapper" : [ {
          "condition" : "OnBeanCondition",
          "message" : "@ConditionalOnMissingBean (types: org.springframework.boot.actuate.endpoint.invoke.ParameterValueMapper; SearchStrategy: all) did not find any beans"
        } ],
        "JacksonEndpointAutoConfiguration#endpointObjectMapper" : [ {
          "condition" : "OnClassCondition",
          "message" : "@ConditionalOnClass found required classes 'com.fasterxml.jackson.databind.ObjectMapper', 'org.springframework.http.converter.json.Jackson2ObjectMapperBuilder'"
        }, {
          "condition" : "OnPropertyCondition",
          "message" : "@ConditionalOnProperty (management.endpoints.jackson.isolated-object-mapper) matched"
        } ],
        "EndpointAutoConfiguration#endpointCachingOperationInvokerAdvisor" : [ {
          "condition" : "OnBeanCondition",
          "message" : "@ConditionalOnMissingBean (types: org.springframework.boot.actuate.endpoint.invoker.cache.CachingOperationInvokerAdvisor; SearchStrategy: all) did not find any beans"
        } ]
      },
      "negativeMatches" : {
        "WebFluxEndpointManagementContextConfiguration" : {
          "notMatched" : [ {
            "condition" : "OnWebApplicationCondition",
            "message" : "not a reactive web application"
          } ],
          "matched" : [ {
            "condition" : "OnClassCondition",
            "message" : "@ConditionalOnClass found required classes 'org.springframework.web.reactive.DispatcherHandler', 'org.springframework.http.server.reactive.HttpHandler'"
          } ]
        },
        "GsonHttpMessageConvertersConfiguration.GsonHttpMessageConverterConfiguration" : {
          "notMatched" : [ {
            "condition" : "GsonHttpMessageConvertersConfiguration.PreferGsonOrJacksonAndJsonbUnavailableCondition",
            "message" : "AnyNestedCondition 0 matched 2 did not; NestedCondition on GsonHttpMessageConvertersConfiguration.PreferGsonOrJacksonAndJsonbUnavailableCondition.JacksonJsonbUnavailable NoneNestedConditions 1 matched 1 did not; NestedCondition on GsonHttpMessageConvertersConfiguration.JacksonAndJsonbUnavailableCondition.JsonbPreferred @ConditionalOnProperty (spring.mvc.converters.preferred-json-mapper=jsonb) did not find property 'spring.mvc.converters.preferred-json-mapper'; NestedCondition on GsonHttpMessageConvertersConfiguration.JacksonAndJsonbUnavailableCondition.JacksonAvailable @ConditionalOnBean (types: org.springframework.http.converter.json.MappingJackson2HttpMessageConverter; SearchStrategy: all) found bean 'mappingJackson2HttpMessageConverter'; NestedCondition on GsonHttpMessageConvertersConfiguration.PreferGsonOrJacksonAndJsonbUnavailableCondition.GsonPreferred @ConditionalOnProperty (spring.mvc.converters.preferred-json-mapper=gson) did not find property 'spring.mvc.converters.preferred-json-mapper'"
          } ],
          "matched" : [ ]
        },
        "WebMvcEndpointManagementContextConfiguration#managementHealthEndpointWebMvcHandlerMapping" : {
          "notMatched" : [ {
            "condition" : "OnManagementPortCondition",
            "message" : "Management Port actual port type (SAME) did not match required type (DIFFERENT)"
          } ],
          "matched" : [ ]
        }
      },
      "unconditionalClasses" : [ "org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration", "org.springframework.boot.actuate.autoconfigure.endpoint.jackson.JacksonEndpointAutoConfiguration", "org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration" ]
    }
  }
}
----

=== 响应结构

响应包含应用程序条件评估的详细信息。下表描述了响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`contexts`|`Object`|以 ID 为键的应用程序上下文。
|`pass:[contexts.*.positiveMatches]`|`Object`|具有匹配条件的类和方法。
|`pass:[contexts.*.positiveMatches.*.[\].condition]`|`String`|条件的名称。
|`pass:[contexts.*.positiveMatches.*.[\].message]`|`String`|匹配条件的详细原因。
|`contexts.*.negativeMatches`|`Object`|具有不匹配条件的类和方法。
|`pass:[contexts.*.negativeMatches.*.notMatched]`|`Array`|匹配的条件。
|`pass:[contexts.*.negativeMatches.*.notMatched.[\].condition]`|`String`|条件的名称。
|`pass:[contexts.*.negativeMatches.*.notMatched.[\].message]`|`String`|条件不匹配的详细原因。
|`pass:[contexts.*.negativeMatches.*.matched]`|`Array`|匹配的条件。
|`pass:[contexts.*.negativeMatches.*.matched.[\].condition]`|`String`|条件的名称。
|`pass:[contexts.*.negativeMatches.*.matched.[\].message]`|`String`|匹配条件的详细原因。
|`contexts.*.unconditionalClasses`|`Array`|无条件的自动配置类的名称（如果有）。
|`contexts.*.parentId`|`String`|父应用程序上下文的 ID（如果有）。
|===
