= Info (info)

The `info` endpoint provides general information about the application.

== Retrieving the Info

To retrieve the information about the application, make a `GET` request to `/actuator/info`, as shown in the following curl-based example:

[source,bash]
----
curl 'http://localhost:8080/actuator/info' -i -X GET
----

The resulting response is similar to the following:

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 231

{
  "git" : {
    "branch" : "main",
    "commit" : {
      "id" : "df027cf",
      "time" : "2024-08-22T16:50:11Z"
    }
  },
  "build" : {
    "artifact" : "application",
    "version" : "1.0.3",
    "group" : "com.example"
  }
}
----

=== Response Structure

The response contains general information about the application.
Each section of the response is contributed by an `InfoContributor`.
Spring Boot provides several contributors that are described below.

==== Build Response Structure

The following table describe the structure of the `build` section of the response:

[%autowidth]
|===
|Path|Type|Description
|`artifact`|`String`|Artifact ID of the application, if any.
|`group`|`String`|Group ID of the application, if any.
|`name`|`String`|Name of the application, if any.
|`version`|`String`|Version of the application, if any.
|`time`|`Varies`|Timestamp of when the application was built, if any.
|===

==== Git Response Structure

The following table describes the structure of the `git` section of the response:

[%autowidth]
|===
|Path|Type|Description
|`branch`|`String`|Name of the Git branch, if any.
|`commit`|`Object`|Details of the Git commit, if any.
|`commit.time`|`Varies`|Timestamp of the commit, if any.
|`commit.id`|`String`|ID of the commit, if any.
|===

NOTE: This is the "simple" output.
The contributor can also be configured to output all available data.
