= Liquibase (liquibase)

`liquibase` 端点提供有关 Liquibase 应用的数据库变更集的信息。

== 检索变更

要检索变更，请发送 `GET` 请求到 `/actuator/liquibase`，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/liquibase' -i -X GET
----

得到的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 677

{
  "contexts" : {
    "application" : {
      "liquibaseBeans" : {
        "liquibase" : {
          "changeSets" : [ {
            "author" : "marceloverdijk",
            "changeLog" : "db/changelog/db.changelog-master.yaml",
            "comments" : "",
            "contexts" : [ ],
            "dateExecuted" : "2024-08-22T16:50:15.483Z",
            "deploymentId" : "4345415369",
            "description" : "createTable tableName=customer",
            "execType" : "EXECUTED",
            "id" : "1",
            "labels" : [ ],
            "checksum" : "9:d3589feb2baad02e15540750499ba311",
            "orderExecuted" : 1
          } ]
        }
      }
    }
  }
}
----

=== 响应结构

响应包含应用程序的 Liquibase 变更集的详细信息。下表描述了响应的结构：

|===
|路径|类型|描述
|`contexts`|`Object`|按 ID 键入的应用程序上下文。
|`pass:[contexts.*.liquibaseBeans.*.changeSets]`|`Array`|由 Liquibase beans 制作的变更集，按 bean 名称键入。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].author]`|`String`|变更集的作者。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].changeLog]`|`String`|包含变更集的变更日志。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].comments]`|`String`|变更集的评论。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].contexts]`|`Array`|变更集的上下文。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].dateExecuted]`|`String`|变更集执行的时间戳。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].deploymentId]`|`String`|运行变更集的部署 ID。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].description]`|`String`|变更集的描述。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].execType]`|`String`|变更集的执行类型 (`EXECUTED`, `FAILED`, `SKIPPED`, `RERAN`, `MARK_RAN`)。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].id]`|`String`|变更集的 ID。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].labels]`|`Array`|与变更集相关的标签。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].checksum]`|`String`|变更集的校验和。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].orderExecuted]`|`Number`|变更集的执行顺序。
|`pass:[contexts.*.liquibaseBeans.*.changeSets[\].tag]`|`String`|与变更集相关的标签（如果有）。
|`contexts.*.parentId`|`String`|父应用程序上下文的 ID（如果有）。
|===
