= 日志记录器 (loggers)

`loggers` 端点提供对应用程序日志记录器及其级别配置的访问。

== 检索所有日志记录器

要检索应用程序的所有日志记录器，请发送 `GET` 请求到 `/actuator/loggers`，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/loggers' -i -X GET
----

得到的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 791

{
  "levels" : [ "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE" ],
  "loggers" : {
    "ROOT" : {
      "configuredLevel" : "INFO",
      "effectiveLevel" : "INFO"
    },
    "com.example" : {
      "configuredLevel" : "DEBUG",
      "effectiveLevel" : "DEBUG"
    }
  },
  "groups" : {
    "test" : {
      "configuredLevel" : "INFO",
      "members" : [ "test.member1", "test.member2" ]
    },
    "web" : {
      "members" : [ "org.springframework.core.codec", "org.springframework.http", "org.springframework.web", "org.springframework.boot.actuate.endpoint.web", "org.springframework.boot.web.servlet.ServletContextInitializerBeans" ]
    },
    "sql" : {
      "members" : [ "org.springframework.jdbc.core", "org.hibernate.SQL", "org.jooq.tools.LoggerListener" ]
    }
  }
}
----

=== 响应结构

响应包含请求的日志记录器的详细信息。下表描述了响应的结构：

[%autowidth]
|===
|Path|Type|Description
|`levels`|`Array`|日志系统支持的级别。
|`loggers`|`Object`|按名称键入的日志记录器。
|`groups`|`Object`|按名称键入的日志记录器组。
|`loggers.*.configuredLevel`|`String`|日志记录器的配置级别（如果有）。
|`loggers.*.effectiveLevel`|`String`|日志记录器的有效级别。
|`groups.*.configuredLevel`|`String`|日志记录器组的配置级别（如果有）。
|`groups.*.members`|`Array`|该组的日志记录器。
|===

== 检索单个日志记录器

要检索单个日志记录器，请发送 `GET` 请求到 `pass:[/actuator/loggers/{logger.name}]`，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/loggers/com.example' -i -X GET
----

The resulting response is similar to the following:
上述示例检索了名为 `com.example` 的日志记录器的信息。得到的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 61

{
  "configuredLevel" : "INFO",
  "effectiveLevel" : "INFO"
}
----

=== 响应结构

响应包含请求的日志记录器的详细信息。下表描述了响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`configuredLevel`|`String`|日志记录器的配置级别（如果有）。
|`effectiveLevel`|`String`|日志记录器的有效级别。
|===

== 检索单个组

要检索单个组，请发送 `GET` 请求到 `pass:[/actuator/loggers/{group.name}]`，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/loggers/test' -i -X GET
----

The resulting response is similar to the following:
上述示例检索了名为 `test` 的日志记录器组的信息。得到的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Content-Length: 82

{
  "configuredLevel" : "INFO",
  "members" : [ "test.member1", "test.member2" ]
}
----

=== 响应结构

响应包含请求的组的详细信息。下表描述了响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`configuredLevel`|`String`|日志记录器组的配置级别（如果有）。
|`members`|`Array`|该组的日志记录器。
|===

== 设置日志级别

要设置日志记录器的级别，请发送 `POST` 请求到 `pass:[/actuator/loggers/{logger.name}]`，并附带一个 JSON 请求体，指定日志记录器的配置级别，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/loggers/com.example' -i -X POST \
-H 'Content-Type: application/json' \
-d '{"configuredLevel":"debug"}'
----

上述示例将 `com.example` 日志记录器的 `configuredLevel` 设置为 `DEBUG`。

=== 请求结构

请求指定了日志记录器的所需级别。下表描述了请求的结构：

[%autowidth]
|===
|路径|类型|描述
|`configuredLevel`|`String`|日志记录器的级别。可以省略以清除级别。
|===

== 设置组的日志级别

要设置日志记录器组的级别，请发送 `POST` 请求到 `pass:[/actuator/loggers/{group.name}]`，并附带一个 JSON 请求体，指定日志记录器组的配置级别，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:8080/actuator/loggers/test' -i -X POST \
-H 'Content-Type: application/json' \
-d '{"configuredLevel":"debug"}'
----

上述示例将 `test` 日志记录器组的 `configuredLevel` 设置为 `DEBUG`。

=== 请求结构

请求指定了日志记录器组的所需级别。下表描述了请求的结构：

[%autowidth]
|===
|路径|类型|描述
|`configuredLevel`|`String`|日志记录器的级别。可以省略以清除级别。
|===

== 清除日志级别

要清除日志记录器的级别，请发送 `POST` 请求到 `pass:[/actuator/loggers/{logger.name}]`，并附带一个包含空对象的 JSON 请求体，如下基于 curl 的示例所示：

[source,bash]
----
$ curl 'http://localhost:8080/actuator/loggers/com.example' -i -X POST \
-H 'Content-Type: application/json' \
-d '{}'
----

上述示例清除了 `com.example` 日志记录器的配置级别。






