= 映射 (mappings)

`mappings` 端点提供有关应用程序请求映射的信息。

== 检索映射

要检索映射，请发送 `GET` 请求到 `/actuator/mappings`，如下基于 curl 的示例所示：

[source,bash]
----
curl 'http://localhost:38761/actuator/mappings' -i -X GET \
-H 'accept-encoding: gzip' \
-H 'user-agent: ReactorNetty/1.1.22' \
-H 'accept: */*'
----

得到的响应类似于以下内容：

----
HTTP/1.1 200 OK
Content-Type: application/vnd.spring-boot.actuator.v3+json
Transfer-Encoding: chunked
Date: Thu, 22 Aug 2024 16:50:26 GMT
Content-Length: 5342

{
  "contexts" : {
    "application" : {
      "mappings" : {
        "dispatcherServlets" : {
          "dispatcherServlet" : [ {
            "handler" : "Actuator root web endpoint",
            "predicate" : "{GET [/actuator], produces [application/vnd.spring-boot.actuator.v3+json || application/vnd.spring-boot.actuator.v2+json || application/json]}",
            "details" : {
              "handlerMethod" : {
                "className" : "org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.WebMvcLinksHandler",
                "name" : "links",
                "descriptor" : "(Ljakarta/servlet/http/HttpServletRequest;Ljakarta/servlet/http/HttpServletResponse;)Ljava/util/Map;"
              },
              "requestMappingConditions" : {
                "consumes" : [ ],
                "headers" : [ ],
                "methods" : [ "GET" ],
                "params" : [ ],
                "patterns" : [ "/actuator" ],
                "produces" : [ {
                  "mediaType" : "application/vnd.spring-boot.actuator.v3+json",
                  "negated" : false
                }, {
                  "mediaType" : "application/vnd.spring-boot.actuator.v2+json",
                  "negated" : false
                }, {
                  "mediaType" : "application/json",
                  "negated" : false
                } ]
              }
            }
          }, {
            "handler" : "Actuator web endpoint 'mappings'",
            "predicate" : "{GET [/actuator/mappings], produces [application/vnd.spring-boot.actuator.v3+json || application/vnd.spring-boot.actuator.v2+json || application/json]}",
            "details" : {
              "handlerMethod" : {
                "className" : "org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping.OperationHandler",
                "name" : "handle",
                "descriptor" : "(Ljakarta/servlet/http/HttpServletRequest;Ljava/util/Map;)Ljava/lang/Object;"
              },
              "requestMappingConditions" : {
                "consumes" : [ ],
                "headers" : [ ],
                "methods" : [ "GET" ],
                "params" : [ ],
                "patterns" : [ "/actuator/mappings" ],
                "produces" : [ {
                  "mediaType" : "application/vnd.spring-boot.actuator.v3+json",
                  "negated" : false
                }, {
                  "mediaType" : "application/vnd.spring-boot.actuator.v2+json",
                  "negated" : false
                }, {
                  "mediaType" : "application/json",
                  "negated" : false
                } ]
              }
            }
          }, {
            "handler" : "org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.MappingsEndpointServletDocumentationTests$ExampleController#example()",
            "predicate" : "{POST [/], params [a!=alpha], headers [X-Custom=Foo], consumes [application/json || !application/xml], produces [text/plain]}",
            "details" : {
              "handlerMethod" : {
                "className" : "org.springframework.boot.actuate.autoconfigure.endpoint.web.documentation.MappingsEndpointServletDocumentationTests.ExampleController",
                "name" : "example",
                "descriptor" : "()Ljava/lang/String;"
              },
              "requestMappingConditions" : {
                "consumes" : [ {
                  "mediaType" : "application/json",
                  "negated" : false
                }, {
                  "mediaType" : "application/xml",
                  "negated" : true
                } ],
                "headers" : [ {
                  "name" : "X-Custom",
                  "value" : "Foo",
                  "negated" : false
                } ],
                "methods" : [ "POST" ],
                "params" : [ {
                  "name" : "a",
                  "value" : "alpha",
                  "negated" : true
                } ],
                "patterns" : [ "/" ],
                "produces" : [ {
                  "mediaType" : "text/plain",
                  "negated" : false
                } ]
              }
            }
          }, {
            "handler" : "ResourceHttpRequestHandler [classpath [META-INF/resources/webjars/]]",
            "predicate" : "/webjars/**"
          }, {
            "handler" : "ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]",
            "predicate" : "/**"
          } ]
        },
        "servletFilters" : [ {
          "servletNameMappings" : [ ],
          "urlPatternMappings" : [ "/*" ],
          "name" : "requestContextFilter",
          "className" : "org.springframework.boot.web.servlet.filter.OrderedRequestContextFilter"
        }, {
          "servletNameMappings" : [ ],
          "urlPatternMappings" : [ "/*" ],
          "name" : "formContentFilter",
          "className" : "org.springframework.boot.web.servlet.filter.OrderedFormContentFilter"
        } ],
        "servlets" : [ {
          "mappings" : [ "/" ],
          "name" : "dispatcherServlet",
          "className" : "org.springframework.web.servlet.DispatcherServlet"
        } ]
      }
    }
  }
}
----

=== 响应结构

响应包含应用程序映射的详细信息。响应中找到的项目取决于 web 应用程序的类型（反应式或基于 Servlet）。下表描述了响应的通用元素的结构：

[%autowidth]
|===
|路径|类型|描述
|`contexts`|`Object`|按 ID 键入的应用程序上下文。
|`contexts.*.mappings`|`Object`|上下文中的映射，按映射类型键入。
|`contexts.*.mappings.dispatcherServlets`|`Object`|DispatcherServlet 映射（如果有）。
|`contexts.*.mappings.servletFilters`|`Array`|Servlet 过滤器映射（如果有）。
|`contexts.*.mappings.servlets`|`Array`|Servlet 映射（如果有）。
|`contexts.*.mappings.dispatcherHandlers`|`Object`|DispatcherHandler 映射（如果有）。
|`contexts.*.parentId`|`String`|父应用程序上下文的 ID（如果有）。
|===

以下是可能在 `contexts.*.mappings` 中找到的条目的描述。

== Dispatcher Servlets 响应结构

在使用 Spring MVC 时，响应包含 `contexts.*.mappings.dispatcherServlets` 下的任何 `DispatcherServlet` 请求映射的详细信息。下表描述了该部分响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`*`|`Array`|DispatcherServlet 映射（如果有），按 DispatcherServlet bean 名称键入。
|`*.[].details`|`Object`|有关映射的其他实现特定的详细信息。可选。
|`*.[].handler`|`String`|映射的处理程序。
|`*.[].predicate`|`String`|映射的谓词。
|`*.[].details.handlerMethod`|`Object`|处理此映射请求的方法的详细信息（如果有）。
|`*.[].details.handlerMethod.className`|`Varies`|方法的完全限定名称。
|`*.[].details.handlerMethod.name`|`Varies`|方法的名称。
|`*.[].details.handlerMethod.descriptor`|`Varies`|按照 Java 语言规范指定的方法描述符。
|`*.[].details.requestMappingConditions`|`Object`|请求映射条件的详细信息。
|`*.[].details.requestMappingConditions.consumes`|`Varies`|consumes 条件的详细信息。
|`*.[].details.requestMappingConditions.consumes.[].mediaType`|`Varies`|消耗的媒体类型。
|`*.[].details.requestMappingConditions.consumes.[].negated`|`Varies`|媒体类型是否被否定。
|`*.[].details.requestMappingConditions.headers`|`Varies`|headers 条件的详细信息。
|`*.[].details.requestMappingConditions.headers.[].name`|`Varies`|头的名称。
|`*.[].details.requestMappingConditions.headers.[].value`|`Varies`|头的必需值（如果有）。
|`*.[].details.requestMappingConditions.headers.[].negated`|`Varies`|值是否被否定。
|`*.[].details.requestMappingConditions.methods`|`Varies`|处理的 HTTP 方法。
|`*.[].details.requestMappingConditions.params`|`Varies`|params 条件的详细信息。
|`*.[].details.requestMappingConditions.params.[].name`|`Varies`|参数的名称。
|`*.[].details.requestMappingConditions.params.[].value`|`Varies`|参数的必需值（如果有）。
|`*.[].details.requestMappingConditions.params.[].negated`|`Varies`|值是否被否定。
|`*.[].details.requestMappingConditions.patterns`|`Varies`|识别映射处理路径的模式。
|`*.[].details.requestMappingConditions.produces`|`Varies`|produces 条件的详细信息。
|`*.[].details.requestMappingConditions.produces.[].mediaType`|`Varies`|生成的媒体类型。
|`*.[].details.requestMappingConditions.produces.[].negated`|`Varies`|媒体类型是否被否定。
|===

== Servlets 响应结构

在使用 `Servlet` 堆栈时，响应包含 `contexts.*.mappings.servlets` 下的任何 Servlet 映射的详细信息。下表描述了该部分响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`[].mappings`|`Array`|Servlet 的映射。
|`[].name`|`String`|Servlet 的名称。
|`[].className`|`String`|Servlet 的类名。
|===

== Servlet Filters 响应结构

在使用 Servlet 堆栈时，响应包含 `contexts.*.mappings.servletFilters` 下的任何 `Filter` 映射的详细信息。下表描述了该部分响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`[].servletNameMappings`|`Array`|过滤器映射的 Servlet 名称。
|`[].urlPatternMappings`|`Array`|过滤器映射的 URL 模式。
|`[].name`|`String`|过滤器的名称。
|`[].className`|`String`|过滤器的类名。
|===

== Dispatcher Handlers 响应结构

在使用 Spring WebFlux 时，响应包含 `contexts.*.mappings.dispatcherHandlers` 下的任何 `DispatcherHandler` 请求映射的详细信息。下表描述了该部分响应的结构：

[%autowidth]
|===
|路径|类型|描述
|`*`|`Array`|DispatcherHandler 映射（如果有），按 DispatcherHandler bean 名称键入。
|`*.[].details`|`Object`|有关映射的其他实现特定的详细信息。可选。
|`*.[].handler`|`String`|映射的处理程序。
|`*.[].predicate`|`String`|映射的谓词。
|`*.[].details.requestMappingConditions`|`Object`|请求映射条件的详细信息。
|`*.[].details.requestMappingConditions.consumes`|`Varies`|consumes 条件的详细信息。
|`*.[].details.requestMappingConditions.consumes.[].mediaType`|`Varies`|消耗的媒体类型。
|`*.[].details.requestMappingConditions.consumes.[].negated`|`Varies`|媒体类型是否被否定。
|`*.[].details.requestMappingConditions.headers`|`Varies`|headers 条件的详细信息。
|`*.[].details.requestMappingConditions.headers.[].name`|`Varies`|头的名称。
|`*.[].details.requestMappingConditions.headers.[].value`|`Varies`|头的必需值（如果有）。
|`*.[].details.requestMappingConditions.headers.[].negated`|`Varies`|值是否被否定。
|`*.[].details.requestMappingConditions.methods`|`Varies`|处理的 HTTP 方法。
|`*.[].details.requestMappingConditions.params`|`Varies`|params 条件的详细信息。
|`*.[].details.requestMappingConditions.params.[].name`|`Varies`|参数的名称。
|`*.[].details.requestMappingConditions.params.[].value`|`Varies`|参数的必需值（如果有）。
|`*.[].details.requestMappingConditions.params.[].negated`|`Varies`|值是否被否定。
|`*.[].details.requestMappingConditions.patterns`|`Varies`|识别映射处理路径的模式。
|`*.[].details.requestMappingConditions.produces`|`Varies`|produces 条件的详细信息。
|`*.[].details.requestMappingConditions.produces.[].mediaType`|`Varies`|生成的媒体类型。
|`*.[].details.requestMappingConditions.produces.[].negated`|`Varies`|媒体类型是否被否定。
|`*.[].details.handlerMethod`|`Object`|处理此映射请求的方法的详细信息（如果有）。
|`*.[].details.handlerMethod.className`|`String`|方法的完全限定名称。
|`*.[].details.handlerMethod.name`|`String`|方法的名称。
|`*.[].details.handlerMethod.descriptor`|`String`|按照 Java 语言规范指定的方法描述符。
|`*.[].details.handlerFunction`|`Object`|处理此映射请求的函数的详细信息（如果有）。
|`*.[].details.handlerFunction.className`|`String`|函数的完全限定名称。
|===
